export const ARTICLE_LIST = [
    "United States",
    "Donald Trump",
    "Elizabeth II",
    "India",
    "Barack Obama",
    "Cristiano Ronaldo",
    "World War II",
    "United Kingdom",
    "Michael Jackson",
    "Elon Musk",
    "Cleopatra",
    "Lady Gaga",
    "Eminem",
    "Lionel Messi",
    "Game of Thrones",
    "World War I",
    "The Beatles",
    "Justin Bieber",
    "Canada",
    "Freddie Mercury",
    "Kim Kardashian",
    "Johnny Depp",
    "Steve Jobs",
    "Dwayne Johnson",
    "Michael Jordan",
    "Australia",
    "The Big Bang Theory",
    "Taylor Swift",
    "Stephen Hawking",
    "China",
    "Malware",
    "Russia",
    "New York City",
    "Japan",
    "Kanye West",
    "Abraham Lincoln",
    "LeBron James",
    "Charles III",
    "Darth Vader",
    "Star Wars",
    "Miley Cyrus",
    "Germany",
    "September 11 attacks",
    "Leonardo DiCaprio",
    "Kobe Bryant",
    "Selena Gomez",
    "Joe Biden",
    "Harry Potter",
    "France",
    "Breaking Bad",
    "Earth",
    "Titanic",
    "William Shakespeare",
    "Chernobyl Disaster",
    "Muhammad Ali",
    "Winston Churchhill",
    "Sun",
    "Moon",
    "Black Hole",
    "Mercury",
    "Venus",
    "Mars",
    "Jupiter",
    "Saturn",
    "Neptune",
    "Pluto",
    "Milky Way",
    "Solar Eclipse",
    "Galaxy",
    "Lunar Eclipse",
    "Mount Everest",
    "Africa",
    "North America",
    "South America",
    "Europe",
    "Asia",
    "Australia",
    "Climate Change",
    "Grand Canyon",
    "Antarctica",
    "Tsunami",
    "Hurricane",
    "Tornado",
    "Volcano",
    "Continent",
    "Ocean",
    "Pacific Ocean",
    "Atlantic Ocean",
    "Indian Ocean",
    "Arctic Ocean",
    "Lightning",
    "Thunder",
    "Ice Age",
    "Cat",
    "Dog",
    "Animal",
    "Human",
    "Lion",
    "Tiger",
    "Bear",
    "Dinosaur",
    "Elephant",
    "Horse",
    "Evolution",
    "Photosynthesis",
    "Bird",
    "Mammal",
    "Fish",
    "Snake",
    "Spider",
    "Rabbit",
    "Platypus",
    "Chicken",
    "Bear",
    "Giraffe",
    "Octopus",
    "Whale",
    "Raccoon",
    "Eagle",
    "Hawk",
    "Dodo",
    "Virus",
    "Carrot",
    "Potato",
    "Tomato",
    "Cabbage",
    "Lettuce",
    "Apple",
    "Pear",
    "Banana",
    "Grape",
    "Blueberry",
    "Dolphin",
    "Jaguar",
    "Albert Einstein",
    "David Bowie",
    "George Washington",
    "Batman",
    "Spider-Man",
    "Superman",
    "Iron Man",
    "Captain America",
    "Santa Claus",
    "God",
    "Mickey Mouse",
    "Satan",
    "Mario",
    "Dragon",
    "Wonder Woman",
    "Biology",
    "University of Delaware",
    "Delaware",
    "Science",
    "Mathematics",
    "Algebra",
    "Geometry",
    "Calculus",
    "Engineering",
    "Computer Science",
    "Medicine",
    "Finance",
    "Game Theory",
    "Economics",
    "Pseudoscience",
    "Number Theory",
    "Logic",
    "Molecule",
    "Ecology",
    "Charles Darwin",
    "Fungus",
    "Plant",
    "Sugar",
    "Salt",
    "Mineral",
    "Atom",
    "Quartz",
    "Plastic",
    "United Nations",
    "World Health Organizations",
    "Polio",
    "Smallpox",
    "Headache",
    "Obesity",
    "Calorie",
    "Bacteria",
    "Soil",
    "Sociology",
    "Society",
    "Gender",
    "Language",
    "Archaeology",
    "Linguistics",
    "Paleontology",
    "Vertebrate",
    "Brain",
    "Muscle",
    "Creativity",
    "Jewellery",
    "Necklace",
    "Bronze",
    "Copper",
    "Silver",
    "Gold",
    "Coin",
    "Seashell",
    "Lobster",
    "Tide",
    "Joke",
    "Pun",
    "Music",
    "Sound",
    "Opera",
    "Drum",
    "Guitar",
    "Blues",
    "Jazz",
    "Rock Music",
    "Piano",
    "Book",
    "Library",
    "Memory"
]
