export const ARTICLE_LIST = [
    "United_States",
    "Donald_Trump",
    "Elizabeth II",
    "India",
    "Barack Obama",
    "Cristiano Ronaldo",
    "World War II",
    "United Kingdom",
    "Michael Jackson",
    "Elon Musk",
    "Sex",
    "Cleopatra",
    "Lady Gaga",
    "Eminem",
    "Lionel Messi",
    "Game of Thrones",
    "World War I",
    "The Beatles",
    "Justin Bieber",
    "Canada",
    "Freddie Mercury",
    "Kim Kardashian",
    "Johnny Depp",
    "Steve Jobs",
    "Dwayne Johnson",
    "Michael Jordan",
    "Australia",
    "List of presidents of the United States",
    "The Big Bang Theory",
    "Taylor Swift",
    "Stephen Hawking",
    "List of highest-grossing films",
    "China",
    "Malware",
    "Russia",
    "New York City",
    "Japan",
    "Kanye West",
    "List of Marvel Cinematic Universe films",
    "Abraham Lincoln",
    "LeBron James",
    "Charles III",
    "Darth Vader",
    "Star Wars",
    "Miley Cyrus",
    "Germany",
    "September 11 attacks",
    "Leonardo DiCaprio",
    "Kobe Bryant",
    "Selena Gomez",
    "Joe Biden"
]
